# Generated by Django 5.2.17 on 2026-09-26 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixtureRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="dogfood-fixtures", max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("track", "Track"),
                            ("user", "User"),
                            ("team", "Team"),
                            ("project", "Project"),
                        ],
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("object_id", models.BigIntegerField()),
                ("duplicate_of", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "kind", "external_id"),
                        name="fixture_ref_unique",
                    )
                ],
            },
        ),
    ]
