# Generated by Django 5.2.17 on 2026-09-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureref',
            name='kind',
            field=models.CharField(choices=[('event', 'Event'), ('track', 'Track'), ('user', 'User'), ('team', 'Team'), ('project', 'Project'), ('score', 'Score'), ('judge', 'Judge')], max_length=10),
        ),
    ]
