# Generated by Django 5.2.17 on 2026-09-28 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_event_comments_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignSigningKey',
            fields=[
                ('kid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('alg', models.CharField(default='Ed25519', max_length=16)),
                ('public_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('imported_from', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['imported_at', 'kid'],
                'constraints': [models.CheckConstraint(condition=models.Q(('alg', 'Ed25519')), name='foreign_key_alg_ed25519')],
            },
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('kid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('alg', models.CharField(default='Ed25519', max_length=16)),
                ('public_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'kid'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('alg',), name='signing_key_one_active'), models.CheckConstraint(condition=models.Q(('alg', 'Ed25519')), name='signing_key_alg_ed25519')],
            },
        ),
        migrations.CreateModel(
            name='IssuedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('judge_participation', 'Judge participation'), ('participant', 'Participant'), ('winner', 'Winner')], max_length=24)),
                ('slot', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField()),
                ('payload_text', models.TextField()),
                ('signature', models.CharField(max_length=128)),
                ('kid', models.CharField(max_length=16)),
                ('is_foreign', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_records', to='events.event')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at', 'id'],
                'indexes': [models.Index(fields=['subject_user', '-issued_at'], name='record_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('event', 'subject_user', 'kind', 'slot'), name='record_one_active_per_slot'), models.CheckConstraint(condition=models.Q(models.Q(('revoke_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), models.Q(('revoke_reason', ''), _negated=True)), _connector='OR'), name='record_revoke_fields_together'), models.CheckConstraint(condition=models.Q(('kind__in', ['judge_participation', 'participant', 'winner'])), name='record_kind_valid')],
            },
        ),
    ]
