# Generated by Django 5.2.17 on 2026-09-28 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_comments_enabled'),
        ('records', '0003_foreign_key_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issuedrecord',
            name='record_revoke_fields_together',
        ),
        migrations.AddField(
            model_name='issuedrecord',
            name='revoke_category',
            field=models.CharField(blank=True, choices=[('superseded', 'superseded by a newer record'), ('no_longer_eligible', 'no longer eligible'), ('organizer', 'revoked by the organizer')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='issuedrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoke_category', ''), ('revoke_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True)), models.Q(('revoked_at__isnull', False), models.Q(('revoke_reason', ''), _negated=True), models.Q(('revoke_category', ''), _negated=True)), _connector='OR'), name='record_revoke_fields_together'),
        ),
    ]
