# Generated by Django 5.2.17 on 2026-09-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_open_judge_invites'),
        ('projects', '0002_deadline_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='events.event')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BallotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('shown_position', models.PositiveSmallIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='voting.ballot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_lines', to='projects.project')),
            ],
            options={
                'ordering': ['ballot', 'shown_position'],
            },
        ),
        migrations.CreateModel(
            name='VotingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('original_closes_at', models.DateTimeField(blank=True, null=True)),
                ('access_mode', models.CharField(choices=[('authenticated', 'Logged-in accounts'), ('email_gated', 'Email allowlist (one link per email)'), ('open_link', 'Open link (weakest: can be gamed)')], default='authenticated', max_length=20)),
                ('method', models.CharField(choices=[('one_person_one_vote', 'One person, one vote'), ('quadratic', 'Quadratic (influence = square root of credits)')], default='quadratic', max_length=24)),
                ('credit_budget', models.PositiveSmallIntegerField(default=16)),
                ('accounts_before_open_only', models.BooleanField(default=True, help_text='Refuse accounts created at or after voting opens (makes sign-up stuffing harder).')),
                ('ballot_secret', models.CharField(editable=False, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_user__isnull', False)), fields=('event', 'voter_user'), name='ballot_one_per_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('voter_user__isnull', False)), name='ballot_has_a_voter'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False)), _connector='OR'), name='ballot_void_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='ballotline',
            constraint=models.UniqueConstraint(fields=('ballot', 'project'), name='ballotline_one_per_project'),
        ),
        migrations.AddConstraint(
            model_name='ballotline',
            constraint=models.UniqueConstraint(fields=('ballot', 'shown_position'), name='ballotline_one_per_position'),
        ),
        migrations.AddConstraint(
            model_name='ballotline',
            constraint=models.CheckConstraint(condition=models.Q(('credits__lte', 1000)), name='ballotline_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='voting_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('access_mode__in', ['authenticated', 'email_gated', 'open_link'])), name='voting_access_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['one_person_one_vote', 'quadratic'])), name='voting_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('credit_budget__gte', 1), ('credit_budget__lte', 1000)), name='voting_credit_budget_range'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'one_person_one_vote'), _negated=True), ('credit_budget', 1), _connector='OR'), name='voting_one_person_one_vote_budget_is_1'),
        ),
    ]
