# Generated by Django 5.2.17 on 2026-09-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_open_judge_invites'),
        ('voting', '0002_voting_window_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nonce', models.CharField(editable=False, max_length=32)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['event', 'email'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ballot',
            name='ballot_has_a_voter',
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter_cookie',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='votingconfig',
            name='open_link_nonce',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='voterlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voterlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_links', to='events.event'),
        ),
        migrations.AddField(
            model_name='voterlink',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.voterlink'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_link__isnull', False)), fields=('event', 'voter_link'), name='ballot_one_per_link_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_cookie', ''), _negated=True), fields=('event', 'voter_cookie'), name='ballot_one_per_cookie_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('voter_cookie', ''), ('voter_link__isnull', True), ('voter_user__isnull', False)), models.Q(('voter_cookie', ''), ('voter_link__isnull', False), ('voter_user__isnull', True)), models.Q(('voter_link__isnull', True), ('voter_user__isnull', True), models.Q(('voter_cookie', ''), _negated=True)), _connector='OR'), name='ballot_has_exactly_one_voter'),
        ),
        migrations.AddConstraint(
            model_name='voterlink',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='voterlink_one_per_email_per_event'),
        ),
    ]
