# Generated by Django 5.2.17 on 2026-09-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_open_judge_invites'),
        ('projects', '0002_deadline_trigger'),
        ('voting', '0004_trigger_refuses_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='events.event'),
        ),
        migrations.AlterField(
            model_name='ballotline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_lines', to='projects.project'),
        ),
    ]
