# Generated by Django 5.2.17 on 2026-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_protect_ballots'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='created_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
