# Generated by Django 5.2.17 on 2026-09-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_open_judge_invites'),
        ('voting', '0006_ballot_created_ip_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votingconfig',
            name='tally_freezes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='VoteTallySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_by_email', models.CharField(max_length=254)),
                ('method', models.CharField(max_length=24)),
                ('budget', models.PositiveSmallIntegerField()),
                ('rows', models.JSONField()),
                ('counts', models.JSONField(default=dict)),
                ('voided_ballot_ids', models.JSONField(default=list)),
                ('input_hash', models.CharField(max_length=64)),
                ('changed_since_previous', models.BooleanField(default=False)),
                ('voided_since_previous', models.JSONField(default=list)),
                ('restored_since_previous', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_tallies', to='events.event')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='voting.votetallysnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
