# Generated by Django 5.2.17 on 2026-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_tally_immutable_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetallysnapshot',
            name='imported_from',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='votetallysnapshot',
            name='changed_since_previous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
