# Generated by Django 5.2.17 on 2026-09-25 21:14

import core.clock
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='One line, at most 140 characters.', max_length=140, validators=[django.core.validators.MaxLengthValidator(140)])),
                ('description', models.TextField(blank=True, help_text='Markdown. Rendered through markdown-it-py and sanitized with nh3.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Verified with Pillow on upload; never trusted by file extension.', null=True, upload_to='thumbnails/')),
                ('demo_video_url', models.URLField(blank=True, validators=[projects.validators.validate_web_url])),
                ('repo_url', models.URLField(blank=True, validators=[projects.validators.validate_web_url])),
                ('live_url', models.URLField(blank=True, validators=[projects.validators.validate_web_url])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Set once, when the project is first submitted. Later edits do not change it.', null=True)),
                ('hidden_by_organizer', models.BooleanField(default=False, help_text='Organizer moderation. Hides the project from the gallery without deleting it.')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Points at the earlier, canonical submission. Null for canonical rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='projects.project')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team')),
                ('track', models.ForeignKey(blank=True, help_text='Optional while a draft; required to submit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='events.track')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.customquestion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('alt_text', models.CharField(blank=True, help_text='Described for screen readers. Empty means decorative.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='projects.project')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='projects.tag')),
            ],
            options={
                'ordering': ['project', 'tag'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['event', 'status'], name='project_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['event', 'track'], name='project_event_track_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='project_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('duplicate_of__isnull', True)), fields=('event', 'team'), name='project_one_active_per_team_per_event'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), ('submitted_at__isnull', False)), models.Q(('status', 'draft'), ('submitted_at__isnull', True)), _connector='OR'), name='project_submitted_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='customanswer',
            constraint=models.UniqueConstraint(fields=('project', 'question'), name='customanswer_unique_per_question'),
        ),
        migrations.AddConstraint(
            model_name='projecttag',
            constraint=models.UniqueConstraint(fields=('project', 'tag'), name='projecttag_unique_pair'),
        ),
    ]
