# Generated by Django 5.2.17 on 2026-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_content_type',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
