# Generated by Django 5.2.17 on 2026-09-28 13:01

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_deadline_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hide_reason', models.CharField(blank=True, max_length=300)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at', '-id'], name='comment_project_newest_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 2000), models.Q(('body', ''), _negated=True)), name='comment_body_length'), models.CheckConstraint(condition=models.Q(models.Q(('hidden_at__isnull', True), ('hidden_by__isnull', True), ('hide_reason', '')), models.Q(('hidden_at__isnull', False), ('hidden_by__isnull', False), models.Q(('hide_reason', ''), _negated=True)), _connector='OR'), name='comment_hidden_fields_together')],
            },
        ),
    ]
