# Generated by Django 5.2.17 on 2026-09-25 20:54

import accounts.models
import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Login identifier. Stored lowercased.', max_length=254, unique=True)),
                ('display_name', models.CharField(help_text="Shown in the gallery next to the team's projects.", max_length=120)),
                ('is_platform_admin', models.BooleanField(default=False, help_text='Platform operator: full access, including the Django admin.')),
                ('can_create_events', models.BooleanField(default=False, help_text='May create new events. Granted by a platform admin.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Required by django.contrib.admin. Kept in step with is_platform_admin.')),
                ('external_id', models.CharField(blank=True, help_text='Stable id from an import (e.g. jdg_02). Null for portal signups.', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this token is for, e.g. 'acceptance checker'.", max_length=120)),
                ('token_hash', models.CharField(editable=False, help_text='SHA-256 hex digest of the token. The plaintext is never stored.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
