# Generated by Django 5.2.17 on 2026-09-26 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Markdown.')),
                ('starts_at', models.DateTimeField()),
                ('submissions_open_at', models.DateTimeField()),
                ('submissions_close_at', models.DateTimeField()),
                ('original_submissions_close_at', models.DateTimeField(blank=True, null=True)),
                ('judging_ends_at', models.DateTimeField()),
                ('min_team_size', models.PositiveSmallIntegerField(default=1, help_text='A team needs at least this many members to submit.')),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submissions_close_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('short', 'Short text'), ('long', 'Long text'), ('url', 'Link'), ('choice', 'Single choice'), ('checkbox', 'Checkbox (yes/no)')], default='short', max_length=10)),
                ('choices', models.TextField(blank=True, help_text='Single choice only: one option per line.')),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer')], max_length=20)),
                ('side', models.GeneratedField(db_persist=True, expression=models.Case(models.When(role__in=['participant'], then=models.Value('competitor')), default=models.Value('staff')), output_field=models.CharField(max_length=16))),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'role', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, help_text='e.g. "$800" or "Swag box"', max_length=60)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 = first place')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, help_text='Leave empty for an overall prize.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='events.track')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.eventmembership')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('submissions_open_at__lt', models.F('submissions_close_at'))), name='event_submissions_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('submissions_close_at__lte', models.F('judging_ends_at'))), name='event_judging_after_submissions'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lte', models.F('submissions_close_at'))), name='event_starts_before_close'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('max_team_size__lte', 20), ('min_team_size__gte', 1), ('min_team_size__lte', models.F('max_team_size'))), name='event_team_size_range'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'role'), name='membership_unique_user_event_role'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['participant', 'judge', 'organizer'])), name='membership_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='track_name_unique_per_event'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('membership', 'track'), name='judge_track_unique'),
        ),
    ]
