# Generated by Django 5.2.17 on 2026-09-25 21:14

import core.clock
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Required by the `membership_no_competitor_and_staff` exclusion constraint further
        # down: Postgres needs btree_gist to use the `<>` operator on a scalar column inside an
        # EXCLUDE constraint. Added by hand rather than by makemigrations, which does not know
        # the constraint needs it.
        #
        # btree_gist ships with postgres-contrib and is present in the postgres:16-alpine image
        # compose uses. Creating an extension needs a role with sufficient privilege; the
        # compose superuser has it. A self-hoster on a locked-down managed database should have
        # a DBA run `CREATE EXTENSION IF NOT EXISTS btree_gist;` once, before migrating --
        # DATA-MODEL.md says so.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL segment, e.g. /events/sample-hack-2026.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(help_text='When the event itself begins (UTC).')),
                ('submissions_open_at', models.DateTimeField(help_text='Writes are refused before this instant (UTC).')),
                ('submissions_close_at', models.DateTimeField(help_text='Writes are refused from this instant onwards (UTC). The instant itself is closed.')),
                ('judging_ends_at', models.DateTimeField(blank=True, help_text='End of the judging window (UTC). Unused in T1; T2 enforces it.', null=True)),
                ('max_team_size', models.PositiveSmallIntegerField(default=4)),
                ('gallery_public', models.BooleanField(default=True, help_text='When false, submitted projects are not shown in the public gallery.')),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="Becomes the event's first organizer. Null only for imported events.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submissions_close_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('url', 'URL'), ('choice', 'Choice'), ('boolean', 'Yes / no')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Allowed values, for kind=choice. Ignored otherwise.')),
                ('required', models.BooleanField(default=False, help_text='Required questions must be answered to submit, not to draft.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_gallery', models.BooleanField(default=False, help_text='When true, the answer is shown publicly on the project page.')),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'ordering': ['event', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('judge', 'Judge'), ('organizer', 'Organizer')], max_length=20)),
                ('side', models.GeneratedField(db_persist=True, expression=models.Case(models.When(role='participant', then=models.Value('competitor')), default=models.Value('staff')), output_field=models.CharField(max_length=16))),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'role', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['event', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value_text', models.CharField(blank=True, help_text="Free text, e.g. '800 USD'. Not a number: prizes are often not cash.", max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display rank.')),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, help_text='Null for an event-wide prize.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.track')),
            ],
            options={
                'ordering': ['event', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.eventmembership')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.track')),
            ],
            options={
                'ordering': ['membership', 'track'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lte', models.F('submissions_open_at'))), name='event_starts_before_submissions_open'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('submissions_open_at__lt', models.F('submissions_close_at'))), name='event_submissions_open_before_close'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('judging_ends_at__isnull', True), ('judging_ends_at__gte', models.F('submissions_close_at')), _connector='OR'), name='event_judging_ends_after_submissions_close'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('max_team_size__gte', 1)), name='event_max_team_size_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'role'), name='membership_unique_user_event_role'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('user', '='), ('event', '='), ('side', '<>')], name='membership_no_competitor_and_staff'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='track_unique_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('membership', 'track'), name='judgetrack_unique_pair'),
        ),
    ]
