# Generated by Django 5.2.17 on 2026-09-26 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                ("starts_at", models.DateTimeField()),
                ("submissions_open_at", models.DateTimeField()),
                ("submissions_close_at", models.DateTimeField()),
                ("judging_ends_at", models.DateTimeField()),
                ("max_team_size", models.PositiveSmallIntegerField(default=4)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submissions_close_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=200)),
                ("help_text", models.CharField(blank=True, max_length=300)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("short", "Short text"),
                            ("long", "Long text"),
                            ("url", "Link"),
                            ("choice", "Single choice"),
                            ("checkbox", "Checkbox (yes/no)"),
                        ],
                        default="short",
                        max_length=10,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True, help_text="Single choice only: one option per line."
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_links",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["added_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                related_name="organized_events",
                through="events.EventOrganizer",
                through_fields=("event", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "value",
                    models.CharField(
                        blank=True, help_text='e.g. "$800" or "Swag box"', max_length=60
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="1 = first place"
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="events.event",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for an overall prize.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prizes",
                        to="events.track",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventorganizer",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_organizer_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("submissions_open_at__lt", models.F("submissions_close_at"))
                ),
                name="event_submissions_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("submissions_close_at__lte", models.F("judging_ends_at"))
                ),
                name="event_judging_after_submissions",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_at__lte", models.F("submissions_close_at"))
                ),
                name="event_starts_before_close",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_team_size__gte", 1), ("max_team_size__lte", 20)
                ),
                name="event_team_size_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="track_name_unique_per_event"
            ),
        ),
    ]
