# Generated by Django 5.2.17 on 2026-09-26 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="event_team_size_range",
        ),
        migrations.AddField(
            model_name="event",
            name="min_team_size",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="A team needs at least this many members to submit.",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_team_size__lte", 20),
                    ("min_team_size__gte", 1),
                    ("min_team_size__lte", models.F("max_team_size")),
                ),
                name="event_team_size_range",
            ),
        ),
    ]
