# Generated by Django 5.2.17 on 2026-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_event_event_team_size_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="original_submissions_close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
