# Generated by Django 5.2.17 on 2026-09-27 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_judging_start_results_strict_timeline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="judgeinvite",
            name="judge_invite_one_pending_per_email",
        ),
        migrations.AlterField(
            model_name="judgeinvite",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="judgeinvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("accepted_at__isnull", True),
                    ("revoked_at__isnull", True),
                    models.Q(("email", ""), _negated=True),
                ),
                fields=("event", "email"),
                name="judge_invite_one_pending_per_email",
            ),
        ),
    ]
