# Generated by Django 5.2.17 on 2026-09-27 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_open_judge_invites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="judgeinvite",
            name="judge_invite_one_pending_per_email",
        ),
        migrations.AddField(
            model_name="judgeinvite",
            name="role",
            field=models.CharField(
                choices=[("judge", "Judge"), ("organizer", "Organizer")],
                default="judge",
                help_text="What accepting makes you: a judge or a co-organizer of the event.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="judgeinvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("accepted_at__isnull", True),
                    ("revoked_at__isnull", True),
                    models.Q(("email", ""), _negated=True),
                ),
                fields=("event", "role", "email"),
                name="judge_invite_one_pending_per_email",
            ),
        ),
    ]
