# Generated by Django 5.2.17 on 2026-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_invite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
