# Generated by Django 5.2.17 on 2026-09-26 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("signup", "Signed up"),
                            ("login_ok", "Logged in"),
                            ("login_failed", "Login failed"),
                            ("login_throttled", "Login refused (throttled)"),
                            ("logout", "Logged out"),
                            ("password_changed", "Changed password"),
                            ("session_revoked", "Revoked a session"),
                            ("sessions_revoked_others", "Signed out other sessions"),
                            ("token_created", "Created an API token"),
                            ("token_revoked", "Revoked an API token"),
                            ("token_rejected", "Rejected an invalid API token"),
                            ("access_denied", "Refused access to a portal"),
                            ("account_created", "Created an account for someone else"),
                        ],
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["action", "subject", "created_at"],
                        name="audit_throttle_idx",
                    ),
                    models.Index(
                        fields=["action", "ip", "created_at"], name="audit_ip_idx"
                    ),
                ],
            },
        ),
    ]
