# Generated by Django 5.2.17 on 2026-09-25 21:14

import core.clock
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login.succeeded', 'Login succeeded'), ('login.failed', 'Login failed'), ('login.throttled', 'Login refused by throttle'), ('account.signup', 'Account created'), ('account.password_changed', 'Password changed'), ('token.created', 'API token created'), ('token.revoked', 'API token revoked'), ('event.created', 'Event created'), ('event.updated', 'Event updated'), ('event.dates_changed', 'Event dates changed'), ('event.membership_added', 'Member added to event'), ('event.membership_removed', 'Member removed from event'), ('event.track_changed', 'Track added, edited or removed'), ('event.prize_changed', 'Prize added, edited or removed'), ('event.question_changed', 'Custom question added, edited or removed'), ('event.registered', 'Registered as a participant'), ('team.created', 'Team created'), ('team.joined', 'Joined a team'), ('team.left', 'Left a team'), ('team.deleted', 'Team deleted'), ('team.captain_transferred', 'Captaincy transferred'), ('invite.created', 'Invite link created'), ('invite.revoked', 'Invite link revoked'), ('invite.refused', 'Invite link refused'), ('project.created', 'Project created'), ('project.updated', 'Project updated'), ('project.submitted', 'Project submitted'), ('project.hidden', 'Project hidden by organizer'), ('project.image_added', 'Project image added'), ('project.image_removed', 'Project image removed'), ('refused.deadline', 'Write refused: submissions closed'), ('refused.permission', 'Write refused: permission denied'), ('import.ran', 'Fixture import ran'), ('seed.ran', 'Demo seed ran')], max_length=64)),
                ('target_type', models.CharField(blank=True, help_text="Model name of the thing acted on, e.g. 'Project'.", max_length=64)),
                ('target_id', models.CharField(blank=True, help_text="Primary key of the target, as a string so it survives the target's deletion.", max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Action-specific detail: old and new values, refusal reasons, IP address.')),
                ('created_at', models.DateTimeField(default=core.clock.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, help_text='Who acted. Null for anonymous or failed-login attempts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='The event this action concerns, when it concerns one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='events.event')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='audit_event_time_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_time_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_time_idx')],
            },
        ),
    ]
