# Generated by Django 5.2.17 on 2026-09-26 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('signup', 'Signed up'), ('login_ok', 'Logged in'), ('login_failed', 'Login failed'), ('login_throttled', 'Login refused (throttled)'), ('logout', 'Logged out'), ('password_changed', 'Changed password'), ('session_revoked', 'Revoked a session'), ('sessions_revoked_others', 'Signed out other sessions'), ('token_created', 'Created an API token'), ('token_revoked', 'Revoked an API token'), ('token_rejected', 'Rejected an invalid API token'), ('access_denied', 'Refused access to a portal'), ('account_created', 'Created an account for someone else'), ('event_created', 'Created an event'), ('event_updated', 'Edited event settings'), ('event_published', 'Published an event'), ('event_unpublished', 'Unpublished an event'), ('event_part_changed', 'Changed a track, prize or question'), ('organizer_added', 'Added a co-organizer'), ('organizer_removed', 'Removed a co-organizer'), ('judge_added', 'Made someone a judge of an event'), ('judge_removed', 'Removed a judge from an event'), ('team_created', 'Created a team'), ('team_joined', 'Joined a team'), ('team_join_refused', 'Refused a team join'), ('team_left', 'Left a team'), ('team_member_removed', 'Removed a team member'), ('team_captain_changed', 'Handed over captaincy'), ('team_renamed', 'Renamed a team'), ('team_link_reset', "Replaced a team's invite link"), ('team_disbanded', 'Disbanded a team'), ('project_created', 'Started a project'), ('project_updated', 'Edited a project'), ('project_submitted', 'Submitted a project'), ('project_unsubmitted', 'Withdrew a submission to draft'), ('project_image_added', 'Added a project image'), ('project_image_removed', 'Removed a project image'), ('late_write_refused', 'Refused a write after the deadline'), ('early_write_refused', 'Refused a write before submissions opened'), ('deadline_changed', 'Changed the submission deadline'), ('deadline_extended', 'Extended the deadline for everyone'), ('team_extension_granted', 'Granted a team an extension'), ('team_extension_revoked', "Revoked a team's extension"), ('deadline_bypassed', 'Wrote past the deadline (organizer bypass)'), ('fixtures_imported', 'Imported the fixture dataset')], max_length=40)),
                ('subject', models.CharField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'subject', 'created_at'], name='audit_throttle_idx'), models.Index(fields=['action', 'ip', 'created_at'], name='audit_ip_idx')],
            },
        ),
    ]
