# Generated by Django 5.2.17 on 2026-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login.succeeded', 'Login succeeded'), ('login.failed', 'Login failed'), ('login.throttled', 'Login refused by throttle'), ('account.logout', 'Signed out'), ('account.signup', 'Account created'), ('account.password_changed', 'Password changed'), ('token.created', 'API token created'), ('token.revoked', 'API token revoked'), ('event.created', 'Event created'), ('event.updated', 'Event updated'), ('event.dates_changed', 'Event dates changed'), ('event.membership_added', 'Member added to event'), ('event.membership_removed', 'Member removed from event'), ('event.track_changed', 'Track added, edited or removed'), ('event.prize_changed', 'Prize added, edited or removed'), ('event.question_changed', 'Custom question added, edited or removed'), ('event.registered', 'Registered as a participant'), ('team.created', 'Team created'), ('team.renamed', 'Team renamed'), ('team.joined', 'Joined a team'), ('team.left', 'Left a team'), ('team.deleted', 'Team deleted'), ('team.captain_transferred', 'Captaincy transferred'), ('invite.created', 'Invite link created'), ('invite.revoked', 'Invite link revoked'), ('invite.refused', 'Invite link refused'), ('project.created', 'Project created'), ('project.updated', 'Project updated'), ('project.submitted', 'Project submitted'), ('project.hidden', 'Project hidden by organizer'), ('project.image_added', 'Project image added'), ('project.image_removed', 'Project image removed'), ('refused.deadline', 'Write refused: submissions closed'), ('refused.permission', 'Write refused: permission denied'), ('import.ran', 'Fixture import ran'), ('seed.ran', 'Demo seed ran')], max_length=64),
        ),
    ]
