# Generated by Django 5.2.17 on 2026-09-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Signed up'), ('login_ok', 'Logged in'), ('login_failed', 'Login failed'), ('login_throttled', 'Login refused (throttled)'), ('logout', 'Logged out'), ('password_changed', 'Changed password'), ('session_revoked', 'Revoked a session'), ('sessions_revoked_others', 'Signed out other sessions'), ('token_created', 'Created an API token'), ('token_revoked', 'Revoked an API token'), ('token_rejected', 'Rejected an invalid API token'), ('access_denied', 'Refused access to a portal'), ('account_created', 'Created an account for someone else'), ('event_created', 'Created an event'), ('event_updated', 'Edited event settings'), ('event_published', 'Published an event'), ('event_unpublished', 'Unpublished an event'), ('event_part_changed', 'Changed a track, prize or question'), ('organizer_added', 'Added a co-organizer'), ('organizer_removed', 'Removed a co-organizer'), ('judge_added', 'Made someone a judge of an event'), ('judge_removed', 'Removed a judge from an event'), ('team_created', 'Created a team'), ('team_joined', 'Joined a team'), ('team_join_refused', 'Refused a team join'), ('team_left', 'Left a team'), ('team_member_removed', 'Removed a team member'), ('team_captain_changed', 'Handed over captaincy'), ('team_renamed', 'Renamed a team'), ('team_link_reset', "Replaced a team's invite link"), ('team_disbanded', 'Disbanded a team'), ('project_created', 'Started a project'), ('project_updated', 'Edited a project'), ('project_submitted', 'Submitted a project'), ('project_unsubmitted', 'Withdrew a submission to draft'), ('project_image_added', 'Added a project image'), ('project_image_removed', 'Removed a project image'), ('late_write_refused', 'Refused a write after the deadline'), ('early_write_refused', 'Refused a write before submissions opened'), ('deadline_changed', 'Changed the submission deadline'), ('deadline_extended', 'Extended the deadline for everyone'), ('team_extension_granted', 'Granted a team an extension'), ('team_extension_revoked', "Revoked a team's extension"), ('deadline_bypassed', 'Wrote past the deadline (organizer bypass)'), ('fixtures_imported', 'Imported the fixture dataset'), ('snapshot_created', 'Computed a results snapshot'), ('snapshot_refused', 'Refused to compute a results snapshot'), ('scoring_config_changed', "Changed an event's scoring configuration"), ('scoring_config_refused', "Refused a change to an event's scoring configuration")], max_length=40),
        ),
    ]
