#!/usr/bin/env python3
"""The Normalization Proof section of JUDGING.md, generated from the organizers' fixture file.

    PYTHONPATH=src python scripts/normalization_proof.py              # print the section
    PYTHONPATH=src python scripts/normalization_proof.py --write      # replace it in JUDGING.md

The scoring engine only (no database, no Django): the fixture file is read the way the engine's CLI
reads it, M2 and the raw mean are run with the default configuration (whose cross-validation seed is
derived from the event id), and the section is printed between the markers in JUDGING.md. Same file,
same engine, same text: tests/test_normalization_proof.py regenerates it and compares.

For every project M2 ranks, the move from the raw mean splits exactly (scoring/engine/explain.py):

    raw mean - M2 score = mean lean of its reviewers   (judge-lean correction)
                        + mean residual of its reviews (shrinkage towards the mean)
"""

import os
import sys

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "src"))

import json  # noqa: E402

from scoring.engine.io import load_organizer_file  # noqa: E402
from scoring.engine.pipeline import compare  # noqa: E402

EQUAL_DECIMALS = 9  # the engine's default: scores equal after rounding are ties
FIXTURES = os.path.join(ROOT, "acceptance", "fixtures.json")
JUDGING = os.path.join(ROOT, "JUDGING.md")
START = "<!-- normalization-proof:start (generated by scripts/normalization_proof.py; do not edit) -->"
END = "<!-- normalization-proof:end -->"
MOVERS = 10


def shared_ranks(scores):
    """{id: 1 + number strictly higher}, equal scores (after rounding) sharing a rank -- the results
    page's rule. The engine's own ordinal rank breaks exact ties by file order, which would count
    file order as movement."""
    rounded = {k: round(v, EQUAL_DECIMALS) for k, v in scores.items()}
    return {k: 1 + sum(1 for w in rounded.values() if w > v) for k, v in rounded.items()}


def generate(path=FIXTURES):
    inp, _log = load_organizer_file(path)
    raw_file = json.loads(open(path, encoding="utf-8").read())
    titles = {p["id"]: p.get("title") or p["id"] for p in raw_file["projects"]}
    comparison = compare(inp, ["m2"], baseline="raw_mean", movers_k=MOVERS)
    m2 = comparison.results["m2"]
    ranked = sorted(m2.projects, key=lambda p: p.rank)
    order = {pid: i for i, pid in enumerate(inp.projects)}
    raw_rank = shared_ranks({p.project_id: p.extras["raw_mean"] for p in ranked})
    m2_rank = shared_ranks({p.project_id: p.score for p in ranked})
    moved = [p for p in ranked if raw_rank[p.project_id] != m2_rank[p.project_id]]
    movers = sorted(ranked, key=lambda p: (-abs(raw_rank[p.project_id] - m2_rank[p.project_id]),
                                           order[p.project_id]))[:MOVERS]
    # the split is exact: check it on every ranked project, and report the largest error
    worst = 0.0
    for p in ranked:
        e = p.extras
        if e.get("raw_mean") is not None:
            worst = max(worst, abs((e["raw_mean"] - p.score) - (e["lean_part"] + e["shrinkage_part"])))
    params = m2.params_chosen["components"]
    judges = len({r.judge_id for r in inp.reviews})

    def name(pid):
        return f"{titles.get(pid, pid)} (`{pid}`)"

    out = [START, "", "## Normalization Proof (the fixture event)", ""]
    out.append(
        f"Generated from `acceptance/fixtures.json` by `scripts/normalization_proof.py` with the engine's "
        f"default configuration: {len(inp.reviews)} reviews by {judges} judges of {len(ranked)} ranked "
        f"projects, in {len(m2.components)} connected component(s). M2's ridge strengths were chosen by "
        f"cross-validation (seed {params[0]['cv_seed']}): "
        + "; ".join(f"component {c['component']}: lambda_q {c['lam_q']:g}, lambda_b {c['lam_b']:g}" for c in params)
        + ".")
    out.append("")
    raw_ties = len(ranked) - len(set(round(p.extras["raw_mean"], EQUAL_DECIMALS) for p in ranked))
    out.append(f"**{len(moved)} of {len(ranked)} projects change rank** between the plain mean of their "
               f"reviews and M2. Ranks here are shared by exact ties, as on the results page: the raw means "
               f"have {raw_ties} exact repeats (many projects average exactly 3.333), and an ordinal rank "
               f"would count their file order as movement. The split below is exact: over every ranked "
               f"project, |(raw - M2) - (lean + shrinkage)| is at most {worst:.1e}.")
    out.append("")
    out.append("### Top 10: raw mean vs M2")
    out.append("")
    out.append("| M2 rank | project | M2 score | ± se | raw rank | raw mean | reviews |")
    out.append("|---:|---|---:|---:|---:|---:|---:|")
    for p in sorted(ranked, key=lambda p: (m2_rank[p.project_id], p.rank))[:10]:
        out.append(f"| {m2_rank[p.project_id]} | {name(p.project_id)} | {p.score:.3f} | {p.se:.3f} | "
                   f"{raw_rank[p.project_id]} | {p.extras['raw_mean']:.3f} | {p.n_reviews} |")
    out.append("")
    out.append(f"### The {MOVERS} biggest moves, and why")
    out.append("")
    out.append("Positive lean = its reviewers score high on everything, so M2 takes that back; "
               "positive shrinkage = its reviews sit above what the model expects, and with few reviews "
               "M2 pulls it towards the mean. raw mean - M2 score = lean + shrinkage.")
    out.append("")
    out.append("| project | reviews | raw rank | M2 rank | move | raw mean | M2 score | lean | shrinkage | mainly |")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|")
    for p in movers:
        e, pid = p.extras, p.project_id
        main = "judge lean" if abs(e["lean_part"]) > abs(e["shrinkage_part"]) else "shrinkage"
        out.append(f"| {name(pid)} | {p.n_reviews} | {raw_rank[pid]} | {m2_rank[pid]} | "
                   f"{raw_rank[pid] - m2_rank[pid]:+d} | {e['raw_mean']:.3f} | {p.score:.3f} | {e['lean_part']:+.3f} | "
                   f"{e['shrinkage_part']:+.3f} | {main} |")
    out.append("")
    leans = sum(1 for p in movers if abs(p.extras["lean_part"]) > abs(p.extras["shrinkage_part"]))
    out.append(f"Of these {len(movers)} moves, {leans} are mainly the judge-lean correction and "
               f"{len(movers) - leans} mainly shrinkage. \"mainly\" compares the two parts' sizes; they can "
               "pull in opposite directions. M2's tie groups (shown on the results page) say which of these "
               "ranks the reviews can actually separate.")
    out.append("")
    out.append(END)
    return "\n".join(out)


def write(section, path=JUDGING):
    text = open(path, encoding="utf-8").read()
    if START in text and END in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        text = before + section + after
    else:
        text = text.rstrip("\n") + "\n\n" + section + "\n"
    open(path, "w", encoding="utf-8", newline="\n").write(text)


def current(path=JUDGING):
    text = open(path, encoding="utf-8").read()
    if START not in text or END not in text:
        return None
    return START + text.split(START, 1)[1].split(END, 1)[0] + END


if __name__ == "__main__":
    section = generate()
    if "--write" in sys.argv:
        write(section)
        print(f"written to {JUDGING}")
    else:
        print(section)
