# Generated by Django 5.2.17 on 2026-09-26 12:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable machine name, e.g. 'functionality'. Matches the fixture's criteria keys.", max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('weight', models.DecimalField(decimal_places=3, default=1, help_text='Relative weight in the weighted average. Decimal, not float: a rubric that sums to 1.000 must still sum to 1.000 after being read back.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_value', models.SmallIntegerField(default=1)),
                ('max_value', models.SmallIntegerField(default=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'criteria',
                'ordering': ['event', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.eventmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'judge'],
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text="Within the criterion's min/max. Decimal so a 0.5-step rubric is possible in T2 without a migration.", max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.criterion')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.score')),
            ],
            options={
                'ordering': ['score', 'criterion__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='criterion_unique_key_per_event'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('min_value__lt', models.F('max_value'))), name='criterion_min_below_max'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['project'], name='score_project_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['judge'], name='score_judge_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('judge', 'project'), name='score_unique_judge_project'),
        ),
        migrations.AddConstraint(
            model_name='scoreitem',
            constraint=models.UniqueConstraint(fields=('score', 'criterion'), name='scoreitem_unique_per_criterion'),
        ),
    ]
