# Generated by Django 5.2.17 on 2026-09-26 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_existing_reviews(apps, schema_editor):
    """Reviews that already exist were imported from the fixtures, so they are complete.

    Each is marked submitted (at the time it was created) and given the assignment it would
    have had, so progress counts and "one review per assignment" hold for old data too. Order
    within a judge's queue follows the review order.
    """
    Score = apps.get_model("scoring", "Score")
    Assignment = apps.get_model("scoring", "Assignment")
    positions = {}
    for score in Score.objects.order_by("judge_id", "created_at", "id").iterator():
        if score.submitted_at is None:
            score.submitted_at = score.created_at
            score.save(update_fields=["submitted_at"])
        position = positions.get(score.judge_id, 0)
        positions[score.judge_id] = position + 1
        Assignment.objects.get_or_create(
            judge_id=score.judge_id, project_id=score.project_id, status="assigned",
            defaults={"source": "import", "position": position, "created_at": score.created_at},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_judging_extension_and_invites"),
        ("projects", "0002_deadline_trigger"),
        ("scoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="What judges should look for under this criterion.",
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="level_descriptions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="score",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AssignmentRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "Initial assignment"),
                            ("top_up", "Top-up to the review target"),
                            ("reassign", "Reassignment of declined or stalled reviews"),
                        ],
                        max_length=12,
                    ),
                ),
                ("seed", models.BigIntegerField()),
                (
                    "target_reviews",
                    models.PositiveSmallIntegerField(
                        help_text="Reviews each project should end up with."
                    ),
                ),
                (
                    "max_load",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Most live assignments one judge may hold; empty = no cap.",
                        null=True,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_rounds",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Imported with an existing review"),
                            ("auto", "Automatic assignment"),
                            ("manual", "Added by an organizer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("declined_conflict", "Declined (conflict of interest)"),
                            ("withdrawn", "Withdrawn by an organizer"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="events.eventmembership",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="scoring.assignmentround",
                    ),
                ),
            ],
            options={
                "ordering": ["judge", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="assignment_project_idx"
                    ),
                    models.Index(
                        fields=["judge", "status"], name="assignment_judge_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["assigned", "declined_conflict"])
                        ),
                        fields=("judge", "project"),
                        name="assignment_one_live_per_judge_project",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["assigned", "declined_conflict", "withdrawn"],
                            )
                        ),
                        name="assignment_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source__in", ["import", "auto", "manual"])
                        ),
                        name="assignment_source_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_existing_reviews, migrations.RunPython.noop),
    ]
