# Generated by Django 5.2.17 on 2026-09-26 18:03

import django.core.validators
from django.db import migrations, models


from decimal import ROUND_DOWN, Decimal

STEP = Decimal("0.001")


def to_percentages(weights):
    """Keep each rubric's proportions, as percentages adding up to exactly 100.000.

    A frozen copy of scoring.services.as_percentages (migrations must not import app code that
    may change later). Rounding leftovers go to the largest weights first; all-zero weights
    split equally, leftovers to the first criteria.
    """
    total = sum(weights)
    if total <= 0:
        base, extra = divmod(100000, len(weights))
        return [(base + (1 if i < extra else 0)) * STEP for i in range(len(weights))]
    rounded = [(w * 100 / total).quantize(STEP, rounding=ROUND_DOWN) for w in weights]
    left = int((Decimal(100) - sum(rounded)) / STEP)
    for i in sorted(range(len(weights)), key=lambda i: (-weights[i], i))[:left]:
        rounded[i] += STEP
    return rounded


def convert_weights(apps, schema_editor):
    """Weights used to be relative (the importer wrote 1, 1, 1). They are now percentages of the
    final score, so each existing rubric is rescaled once, keeping its proportions:
    1 / 1 / 1 becomes 33.334 / 33.333 / 33.333. Rubrics already adding up to 100 are untouched.
    """
    Criterion = apps.get_model("scoring", "Criterion")
    events = Criterion.objects.values_list("event_id", flat=True).distinct()
    for event_id in events:
        criteria = list(Criterion.objects.filter(event_id=event_id).order_by("order", "key", "id"))
        weights = [Decimal(c.weight) for c in criteria]
        if sum(weights) == 100:
            continue
        for criterion, weight in zip(criteria, to_percentages(weights)):
            criterion.weight = weight
            criterion.save(update_fields=["weight"])


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_rubric_descriptions_assignments_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterion",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Percentage of the final score; an event's weights add up to exactly 100 (scoring.services.save_rubric). Decimal, not float: 33.334 + 33.333 + 33.333 must still be 100.000 after being read back.",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RunPython(convert_weights, migrations.RunPython.noop),
    ]
