# Generated by Django 5.2.17 on 2026-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0006_relative_weights"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="criterion",
            name="criterion_min_below_max",
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_value", 5), ("min_value", 1)),
                name="criterion_scale_is_1_to_5",
            ),
        ),
    ]
