# Generated by Django 5.2.17 on 2026-09-27 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_invite_role"),
        ("projects", "0002_deadline_trigger"),
        ("scoring", "0007_scale_is_1_to_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="assignment_status_valid",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("declined_conflict", "Declined (conflict of interest)"),
                    ("withdrawn", "Withdrawn by an organizer"),
                    ("released", "Released (reshuffle or lower target)"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentround",
            name="kind",
            field=models.CharField(
                choices=[
                    ("initial", "Initial assignment"),
                    ("top_up", "Top-up to the review target"),
                    ("reassign", "Reassignment of declined or stalled reviews"),
                    ("reshuffle", "Reshuffle of every unstarted review"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["assigned", "declined_conflict", "withdrawn", "released"],
                    )
                ),
                name="assignment_status_valid",
            ),
        ),
    ]
