# Generated by Django 5.2.17 on 2026-09-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_results_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscoringconfig',
            name='community_weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventscoringconfig',
            name='judge_weight',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='combined',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='final_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
