# Generated by Django 5.2.17 on 2026-09-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_comments_enabled'),
        ('scoring', '0012_released_and_reshuffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='events.eventmembership'),
        ),
    ]
