# Generated by Django 5.2.17 on 2026-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_score_judge_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsnapshot',
            name='imported_from',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
