# Generated by Django 5.2.17 on 2026-09-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment'),
        ('scoring', '0014_snapshot_imported_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='projects.project'),
        ),
    ]
