"""Project drafting, submission, tags, answers and image uploads.

Every function here is a participant write path, so **every one of them calls the deadline guard
first and the permission guard second**, before any transaction opens. See `core/guards.py` for why
that ordering is what makes the audit trail survive a refusal, and `teams/services.py` for the same
shape applied to team formation.

Three rules in this module are easy to break by accident and are therefore stated here:

1. **Every public function guards itself.** `set_tags`, `save_answers`, `add_image`,
   `remove_image` and `set_thumbnail` are not internal helpers that trust `update_project` to
   have checked -- each one is reachable on its own from a view, and a public write that assumes
   its caller guarded is one refactor away from being an unguarded write. `update_project` calls
   the private `_write_*` helpers after its own guards have passed.

2. **The clock is read once per request.** Each entry point takes `now = clock.now()` at the top
   and passes that same instant to the guard and to `submitted_at`. Two reads leave a window in
   which a submission is admitted by the guard and then stamped with a time after the deadline.

3. **The one-active-project rule is enforced by the database.** `create_project` pre-checks and
   raises `ProjectExists`, but the pre-check is a courtesy for the error message; the partial
   unique index `project_one_active_per_team_per_event` is the authority, and the `IntegrityError`
   it raises under a race is mapped to the same 409. Neither path may produce a 500.
"""

from __future__ import annotations

import io
import re
import secrets
import warnings

from django.conf import settings
from django.core.exceptions import ValidationError as DjangoValidationError
from django.core.files.base import ContentFile
from django.db import IntegrityError, transaction
from PIL import Image

from accounts.models import User
from core import audit, clock
from core.errors import ConflictError, ValidationFailed
from core.guards import guard_permission, guard_submissions_open
from core.models import AuditAction
from core.permissions import can_create_project, can_edit_project
from events.models import CustomQuestion, Event, QuestionKind, Track
from projects import search
from projects.models import (
    CustomAnswer,
    Project,
    ProjectImage,
    ProjectStatus,
    ProjectTag,
    Tag,
)
from projects.validators import validate_web_url
from teams.models import Team, TeamMember

# No count limit is specified in the brief. One is imposed anyway: tags feed the gallery's filter
# list and the search vector's weight-B term, and a project carrying two hundred of them would
# dominate both. Ten is more than any real project needs.
MAX_PROJECT_TAGS = 10

TAG_MAX_LENGTH = 60

# Pillow's own default ceiling is ~89 megapixels. Lowered here because a decompression bomb -- a
# few kilobytes on the wire that decode to hundreds of megabytes of pixels -- is the cheapest
# denial of service against an upload endpoint, and no hackathon screenshot needs 40 million
# pixels. Set at import time so it applies to every open in this process, including the probe.
Image.MAX_IMAGE_PIXELS = 40_000_000

# The file extension and Content-Type each verified format is stored and served as. The stored
# name is generated by this module, so the extension is a fact about the decoded image rather
# than anything the uploader claimed.
FORMAT_EXTENSIONS = {"JPEG": "jpg", "PNG": "png", "WEBP": "webp"}
FORMAT_CONTENT_TYPES = {"JPEG": "image/jpeg", "PNG": "image/png", "WEBP": "image/webp"}

# The tags markdown may produce. No `img`: an image in a description would be a remote URL
# fetched by the viewer's browser at render time, which breaks the portal's "renders with the
# network off" rule and leaks every reader's IP to whatever host the author chose. Descriptions
# get prose, lists, code and links; screenshots go through the upload path, which is verified.
MARKDOWN_ALLOWED_TAGS = {
    "p", "br", "hr", "em", "strong", "del", "code", "pre", "blockquote",
    "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "a",
    "table", "thead", "tbody", "tr", "th", "td",
}
MARKDOWN_ALLOWED_ATTRIBUTES = {"a": {"href", "title"}}
MARKDOWN_URL_SCHEMES = {"http", "https", "mailto"}


class ProjectExists(ConflictError):
    """The team already has an active project for this event."""

    code = "project_exists"


# --------------------------------------------------------------------------------------
# text: tags and markdown
# --------------------------------------------------------------------------------------


def normalize_tag(raw: str) -> str:
    """Lowercase, trim, collapse internal whitespace.

    So `React`, ` react ` and `REACT` are one tag rather than three near-duplicates in the
    gallery's filter list. Called before the `Tag` row is looked up, never after.
    """
    return re.sub(r"\s+", " ", (raw or "").strip().lower())


def parse_tags(raw) -> list[str]:
    """Accept either a comma-separated string (the form) or a list (the API), and normalize."""
    if raw is None:
        return []
    values = raw.split(",") if isinstance(raw, str) else list(raw)

    seen: list[str] = []
    for value in values:
        tag = normalize_tag(str(value))
        if tag and tag not in seen:
            seen.append(tag)
    return seen


def render_markdown(text: str) -> str:
    """Render a project description to HTML that is safe to put in a page.

    Two stages, because neither alone is enough: `markdown-it-py` with `html=False` refuses to
    pass raw HTML through, and `nh3` (Rust ammonia) then enforces an allow-list on what the
    renderer itself produced. Links come back with `rel="noopener noreferrer nofollow"` -- the
    first two so a linked page cannot reach back through `window.opener`, `nofollow` because a
    public gallery anyone can post links to is otherwise an SEO donation box.
    """
    import nh3
    from markdown_it import MarkdownIt

    if not (text or "").strip():
        return ""

    rendered = MarkdownIt("commonmark", {"html": False, "linkify": False}).render(text)
    return nh3.clean(
        rendered,
        tags=MARKDOWN_ALLOWED_TAGS,
        attributes=MARKDOWN_ALLOWED_ATTRIBUTES,
        url_schemes=MARKDOWN_URL_SCHEMES,
        link_rel="noopener noreferrer nofollow",
    )


# --------------------------------------------------------------------------------------
# what is still missing before a project can be submitted
# --------------------------------------------------------------------------------------


def missing_to_submit(project: Project, *, grandfather: bool = False) -> list[str]:
    """Labels of everything still missing before this project could be submitted.

    `Project.missing_requirements()` covers the five plain fields; the required custom questions
    need a query, which is why they are counted here.

    Args:
        grandfather: when True, a required question created *after* this project was submitted is
            not counted. An organizer who adds a required question mid-event is changing what a
            *new* submission must contain; they are not retroactively invalidating submissions
            that were complete when they were made. Without this, one organizer edit would lock
            every existing team out of its own edit form until it answered a question that did
            not exist when it submitted.
    """
    missing = list(project.missing_requirements())

    questions = CustomQuestion.objects.filter(event_id=project.event_id, required=True)
    if grandfather and project.submitted_at is not None:
        questions = questions.filter(created_at__lte=project.submitted_at)

    answered = {
        answer.question_id: (answer.value or "").strip() for answer in project.answers.all()
    }
    for question in questions.order_by("order", "id"):
        if not answered.get(question.pk):
            missing.append(f"answer to “{question.prompt}”")

    return missing


def can_submit(project: Project) -> bool:
    """Convenience for templates deciding whether to offer the submit button.

    A courtesy, never the enforcement -- `submit_project` re-checks.
    """
    return not missing_to_submit(project)


# --------------------------------------------------------------------------------------
# creating, editing, submitting
# --------------------------------------------------------------------------------------

_UNSET = object()

# Editable content fields, in the order the edit form shows them.
CONTENT_FIELDS = (
    "name",
    "tagline",
    "description",
    "track",
    "repo_url",
    "demo_video_url",
    "live_url",
)


def _clean_url_fields(project: Project) -> None:
    """http/https only, on every URL a viewer will see rendered as a link."""
    for field in ("repo_url", "demo_video_url", "live_url"):
        try:
            validate_web_url(getattr(project, field) or "")
        except DjangoValidationError as exc:
            raise ValidationFailed(f"{field.replace('_', ' ')}: {exc.messages[0]}") from exc


def _full_clean(project: Project) -> None:
    """Validate the instance, translating Django's exception into a portal refusal.

    `Model.full_clean()` raises `django.core.exceptions.ValidationError`, which the API's exception
    handler knows nothing about -- it would leave the view as an unhandled exception and answer
    **500**. Every field-level refusal has to arrive as a `PortalError` instead, so the API renders
    a 400 with a code and the UI renders the same message in the form.

    `full_clean` also runs `validate_constraints()`, so the one-active-project index is checked here
    in Python as well as by the database. That check and the `IntegrityError` path in
    `create_project` are the same rule seen from two sides: this one catches the ordinary case, the
    other catches the race where two requests both looked and both found nothing.
    """
    try:
        project.full_clean(exclude=["search_vector"])
    except DjangoValidationError as exc:
        if "project_one_active_per_team_per_event" in str(exc):
            raise ProjectExists(
                f"“{project.team.name}” already has a project for this event."
            ) from exc
        messages = []
        for field, errors in getattr(exc, "message_dict", {}).items():
            label = "" if field == "__all__" else f"{field.replace('_', ' ')}: "
            messages.extend(f"{label}{message}" for message in errors)
        raise ValidationFailed(" ".join(messages) or str(exc)) from exc


def _resolve_track(event: Event, track) -> Track | None:
    """Accept a Track, a primary key or None, and refuse one belonging to another event."""
    if track in (None, "", "0"):
        return None
    if isinstance(track, Track):
        resolved = track
    else:
        resolved = Track.objects.filter(pk=track).first()
        if resolved is None:
            raise ValidationFailed("That track does not exist.")
    if resolved.event_id != event.pk:
        raise ValidationFailed("That track belongs to a different event.")
    return resolved


def _apply_fields(project: Project, values: dict) -> list[str]:
    """Copy provided content fields onto the instance. Returns the names that changed."""
    changed = []
    for field in CONTENT_FIELDS:
        if field not in values:
            continue
        new = values[field]
        if field == "track":
            resolved = _resolve_track(project.event, new)
            if (resolved.pk if resolved else None) == project.track_id:
                continue
            project.track = resolved
            changed.append(field)
            continue
        new = (new or "").strip()
        if new == getattr(project, field):
            continue
        setattr(project, field, new)
        changed.append(field)
    return changed


def guard_project_create(*, actor: User, event: Event, request=None):
    """Run the create-a-project checks, in order, and resolve the caller's team.

    Returns:
        `(team, now)` -- the team the caller will create for, and the instant the guard judged
        against, to be passed straight to `create_project`.

    Split out from `create_project` so a caller that has to validate a request body can do so
    **after** these checks rather than before. The API needs exactly that: the deadline must be
    decided before the body is examined, or a late POST carrying an unknown field would be
    reported as a validation error and the participant would never learn they were late. Keeping
    the two halves here rather than inlining the guards in a view means the rule has one home.

    `create_project` runs the same guards again for its own sake -- it is a public function and
    must be safe called directly. Passing `now` through is what stops the second pass from
    reading the clock again.
    """
    now = clock.now()
    guard_submissions_open(
        event, actor=actor, action="create_project", request=request, now=now
    )

    membership = (
        TeamMember.objects.filter(event=event, user=actor).select_related("team").first()
    )
    guard_permission(
        membership is not None,
        actor=actor,
        action="create_project",
        event=event,
        request=request,
        message="You are not on a team in this event. Join or create a team first.",
    )
    return membership.team, now


def create_project(
    *,
    actor: User,
    event: Event,
    team: Team,
    request=None,
    tags=None,
    answers: dict | None = None,
    now=None,
    **fields,
) -> Project:
    """Start a project for `team`. Created as a draft, and a draft needs only a name.

    `now` lets a caller that has already read the clock and guarded (see
    `create_project_for_event`) pass its instant in rather than taking a second reading.
    """
    now = now or clock.now()
    guard_submissions_open(
        event, actor=actor, action="create_project", target=team, request=request, now=now
    )
    guard_permission(
        can_create_project(actor, team),
        actor=actor,
        action="create_project",
        event=event,
        target=team,
        request=request,
        message="Only members of the team can create its project.",
    )

    if team.event_id != event.pk:
        raise ValidationFailed("That team belongs to a different event.")

    # A courtesy check, so the refusal can name the project that already exists. The database
    # constraint below is the actual enforcement -- see this module's docstring.
    existing = Project.objects.filter(event=event, team=team, duplicate_of__isnull=True).first()
    if existing:
        raise ProjectExists(
            f"“{team.name}” already has a project for this event: “{existing.name}”. "
            "Edit that one instead of starting a second.",
            project_id=existing.pk,
        )

    name = (fields.get("name") or "").strip()
    if not name:
        raise ValidationFailed("Give your project a name. Everything else can wait.")

    project = Project(event=event, team=team, status=ProjectStatus.DRAFT, created_at=now)
    _apply_fields(project, {**fields, "name": name})
    _clean_url_fields(project)

    try:
        with transaction.atomic():
            _full_clean(project)
            project.save()
            if tags is not None:
                _write_tags(project, tags)
            if answers:
                _write_answers(project, answers)
    except IntegrityError as exc:
        # Two concurrent creates for one team: the loser lands here rather than 500ing. Only the
        # one-active-project constraint is translated; any other IntegrityError is a real bug and
        # is re-raised, because reporting it as a conflict would hide it behind a plausible
        # message.
        if "project_one_active_per_team_per_event" not in str(exc):
            raise
        raise ProjectExists(f"“{team.name}” already has a project for this event.") from exc

    search.rebuild_search_vector(project)
    audit.record(
        AuditAction.PROJECT_CREATED,
        actor=actor,
        event=event,
        target=project,
        metadata={"name": project.name, "team": team.name},
        request=request,
    )
    return project


def update_project(
    *,
    actor: User,
    project: Project,
    request=None,
    tags=_UNSET,
    answers=_UNSET,
    **fields,
) -> Project:
    """Edit a project's content. Allowed on a submitted project until the deadline.

    A submitted project must stay submittable: an edit that would empty its tagline or drop its
    track is refused, because a submitted row missing its required content would otherwise sit in
    the public gallery. Required questions added *after* submission are grandfathered -- see
    `missing_to_submit`.
    """
    now = clock.now()
    guard_submissions_open(
        project.event,
        actor=actor,
        action="update_project",
        target=project,
        request=request,
        now=now,
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="update_project",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can edit this project.",
    )

    changed = _apply_fields(project, fields)
    if "name" in changed and not project.name.strip():
        raise ValidationFailed("A project always needs a name.")
    _clean_url_fields(project)

    with transaction.atomic():
        _full_clean(project)
        if changed:
            project.save(update_fields=[*changed, "updated_at"])
        if tags is not _UNSET:
            _write_tags(project, tags)
            changed.append("tags")
        if answers is not _UNSET and answers is not None:
            _write_answers(project, answers)
            changed.append("answers")

        if project.is_submitted:
            still_missing = missing_to_submit(project, grandfather=True)
            if still_missing:
                # Raised inside the transaction on purpose: the edit must not land. This is a
                # validation refusal, not a deadline or permission one, so there is no audit row
                # to lose to the rollback.
                raise ValidationFailed(
                    "A submitted project cannot be left incomplete. Still missing: "
                    + ", ".join(still_missing)
                    + "."
                )

    if not changed:
        return project

    search.rebuild_search_vector(project)
    audit.record(
        AuditAction.PROJECT_UPDATED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"fields": sorted(set(changed))},
        request=request,
    )
    return project


def submit_project(*, actor: User, project: Project, request=None) -> Project:
    """Move a draft to submitted. A no-op for an already-submitted project."""
    now = clock.now()
    guard_submissions_open(
        project.event,
        actor=actor,
        action="submit_project",
        target=project,
        request=request,
        now=now,
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="submit_project",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can submit this project.",
    )

    if project.is_submitted:
        # Not an error, and deliberately not a re-stamp: `submitted_at` records the first
        # submission, and later edits never move it.
        return project

    missing = missing_to_submit(project)
    if missing:
        raise ValidationFailed(
            "This project is not ready to submit. Still missing: " + ", ".join(missing) + "."
        )

    project.status = ProjectStatus.SUBMITTED
    # The same instant the guard just approved, not a second reading of the clock.
    project.submitted_at = now
    with transaction.atomic():
        _full_clean(project)
        # Both columns in one write: `project_submitted_at_matches_status` refuses a submitted
        # row without a timestamp, so they can never be saved separately.
        project.save(update_fields=["status", "submitted_at", "updated_at"])

    search.rebuild_search_vector(project)
    audit.record(
        AuditAction.PROJECT_SUBMITTED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"name": project.name, "submitted_at": clock.iso(project.submitted_at)},
        request=request,
    )
    return project


# --------------------------------------------------------------------------------------
# tags
# --------------------------------------------------------------------------------------


def set_tags(*, actor: User, project: Project, tags, request=None) -> list[str]:
    """Replace a project's tags. Public write path, so it guards itself."""
    now = clock.now()
    guard_submissions_open(
        project.event, actor=actor, action="set_tags", target=project, request=request, now=now
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="set_tags",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can change its tags.",
    )

    with transaction.atomic():
        names = _write_tags(project, tags)

    search.rebuild_search_vector(project)
    audit.record(
        AuditAction.PROJECT_UPDATED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"fields": ["tags"], "tags": names},
        request=request,
    )
    return names


def _write_tags(project: Project, tags) -> list[str]:
    """Reconcile `ProjectTag` rows to exactly `tags`. No guards -- callers have run them."""
    names = parse_tags(tags)
    if len(names) > MAX_PROJECT_TAGS:
        raise ValidationFailed(f"At most {MAX_PROJECT_TAGS} tags per project (got {len(names)}).")
    for name in names:
        if len(name) > TAG_MAX_LENGTH:
            raise ValidationFailed(f"“{name[:20]}…” is too long for a tag.")

    wanted = []
    for name in names:
        tag, _ = Tag.objects.get_or_create(name=name)
        wanted.append(tag)

    project.project_tags.exclude(tag__in=wanted).delete()
    existing = set(project.project_tags.values_list("tag_id", flat=True))
    ProjectTag.objects.bulk_create(
        [ProjectTag(project=project, tag=tag) for tag in wanted if tag.pk not in existing]
    )
    return names


# --------------------------------------------------------------------------------------
# custom answers
# --------------------------------------------------------------------------------------


def save_answers(*, actor: User, project: Project, answers: dict, request=None) -> None:
    """Store answers to the event's custom questions. Public write path, so it guards itself."""
    now = clock.now()
    guard_submissions_open(
        project.event,
        actor=actor,
        action="save_answers",
        target=project,
        request=request,
        now=now,
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="save_answers",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can answer its questions.",
    )

    with transaction.atomic():
        _write_answers(project, answers)

    audit.record(
        AuditAction.PROJECT_UPDATED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"fields": ["answers"]},
        request=request,
    )


def _write_answers(project: Project, answers: dict) -> None:
    """Validate and upsert `{question_id: value}`. No guards -- callers have run them."""
    if not answers:
        return

    questions = {
        question.pk: question
        for question in CustomQuestion.objects.filter(event_id=project.event_id)
    }

    for raw_id, raw_value in answers.items():
        try:
            question = questions[int(raw_id)]
        except (KeyError, TypeError, ValueError):
            # Includes a question belonging to another event: from here it simply does not exist.
            raise ValidationFailed("That question is not part of this event.") from None

        value = _clean_answer(question, raw_value)
        CustomAnswer.objects.update_or_create(
            project=project, question=question, defaults={"value": value}
        )


def _clean_answer(question: CustomQuestion, raw) -> str:
    """One text column serves every question kind, so the kind is validated here."""
    if question.kind == QuestionKind.BOOLEAN:
        if isinstance(raw, bool):
            return "true" if raw else "false"
        value = str(raw or "").strip().lower()
        if value in ("true", "yes", "on", "1"):
            return "true"
        if value in ("", "false", "no", "off", "0"):
            return "false"
        raise ValidationFailed(f"“{question.prompt}” takes yes or no.")

    value = str(raw or "").strip()

    if question.kind == QuestionKind.CHOICE:
        if value and value not in [str(choice) for choice in (question.choices or [])]:
            raise ValidationFailed(f"“{value}” is not one of the options for that question.")
        return value

    if question.kind == QuestionKind.URL and value:
        try:
            validate_web_url(value)
        except DjangoValidationError as exc:
            raise ValidationFailed(f"“{question.prompt}”: {exc.messages[0]}") from exc

    if question.kind == QuestionKind.SHORT_TEXT and len(value) > 300:
        raise ValidationFailed(f"“{question.prompt}” takes at most 300 characters.")

    return value


# --------------------------------------------------------------------------------------
# images
# --------------------------------------------------------------------------------------


def verify_image(upload) -> tuple[ContentFile, str, str]:
    """Verify an upload with Pillow and return storable bytes, format and content type.

    An upload is hostile input, so every claim it makes about itself is ignored: the extension,
    the filename and the browser's declared content type play no part. What the file *decodes to*
    is the only thing consulted.

    Returns:
        `(content, format, content_type)`, where `content` is a **re-encoded** ContentFile and not
        the bytes that were uploaded. Re-encoding is deliberate, for two reasons. It strips
        metadata, including the EXIF GPS tags a phone camera attaches, which a team demoing from
        their kitchen did not mean to publish. And it neutralises polyglots: a file that is a
        valid JPEG *and* carries an HTML or script payload after the image data passes a format
        check, but does not survive a decode-and-re-encode, because only the pixels are copied.
    """
    limit_mb = settings.MAX_UPLOAD_BYTES // (1024 * 1024)
    size = getattr(upload, "size", None)
    if size is not None and size > settings.MAX_UPLOAD_BYTES:
        raise ValidationFailed(f"Images must be {limit_mb} MB or smaller.")

    upload.seek(0)
    data = upload.read()
    if len(data) > settings.MAX_UPLOAD_BYTES:
        raise ValidationFailed(f"Images must be {limit_mb} MB or smaller.")
    if not data:
        raise ValidationFailed("That file was empty.")

    allowed = ", ".join(settings.ALLOWED_IMAGE_FORMATS)
    with warnings.catch_warnings():
        # Pillow only *warns* between MAX_IMAGE_PIXELS and twice that, and raises beyond it. A
        # warning that scrolls past in a log is not a refusal, so it is promoted to an error.
        warnings.simplefilter("error", Image.DecompressionBombWarning)
        try:
            probe = Image.open(io.BytesIO(data))
            fmt = (probe.format or "").upper()
            probe.verify()
        except (Image.DecompressionBombWarning, Image.DecompressionBombError) as exc:
            raise ValidationFailed(
                "That image decodes to too many pixels to process safely."
            ) from exc
        except Exception as exc:  # noqa: BLE001 - any decode failure is the same refusal
            raise ValidationFailed(
                f"That file is not a readable image. Upload a {allowed} file."
            ) from exc

        if fmt not in settings.ALLOWED_IMAGE_FORMATS:
            raise ValidationFailed(
                f"{fmt or 'That format'} is not accepted. Upload a {allowed} file."
            )

        # `verify()` leaves the image object unusable -- any further access raises "operation on
        # closed image". The file has to be rewound and reopened before it can be read for real.
        upload.seek(0)
        try:
            image = Image.open(io.BytesIO(data))
            image.load()
        except (Image.DecompressionBombWarning, Image.DecompressionBombError) as exc:
            raise ValidationFailed(
                "That image decodes to too many pixels to process safely."
            ) from exc
        except Exception as exc:  # noqa: BLE001
            raise ValidationFailed(
                f"That file is not a readable image. Upload a {allowed} file."
            ) from exc

    buffer = io.BytesIO()
    save_kwargs: dict = {}
    if fmt == "JPEG":
        # JPEG has no alpha channel, so a transparent source would fail to save.
        if image.mode not in ("RGB", "L"):
            image = image.convert("RGB")
        save_kwargs = {"quality": 88, "optimize": True}
    elif image.mode == "P":
        image = image.convert("RGBA")
    image.save(buffer, format=fmt, **save_kwargs)

    if buffer.tell() > settings.MAX_UPLOAD_BYTES:
        raise ValidationFailed(f"Images must be {limit_mb} MB or smaller.")

    name = f"{secrets.token_urlsafe(16)}.{FORMAT_EXTENSIONS[fmt]}"
    return ContentFile(buffer.getvalue(), name=name), fmt, FORMAT_CONTENT_TYPES[fmt]


def add_image(*, actor: User, project: Project, upload, alt_text: str = "", request=None):
    """Attach one gallery image. Public write path, so it guards itself."""
    now = clock.now()
    guard_submissions_open(
        project.event, actor=actor, action="add_image", target=project, request=request, now=now
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="add_image",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can add images.",
    )

    content, _fmt, content_type = verify_image(upload)

    with transaction.atomic():
        # The row lock is the enforcement, not a nicety. "At most N rows per parent" cannot be
        # expressed as a database constraint, so the count has to be taken and acted on with
        # nothing else inserting in between. Under READ COMMITTED two concurrent uploads would
        # otherwise both read 7 and both insert, leaving 9 images.
        locked = Project.objects.select_for_update().get(pk=project.pk)
        count = ProjectImage.objects.filter(project=locked).count()
        if count >= settings.MAX_PROJECT_IMAGES:
            raise ValidationFailed(
                f"A project can have at most {settings.MAX_PROJECT_IMAGES} images. "
                "Remove one before adding another."
            )

        image = ProjectImage(
            project=locked,
            alt_text=(alt_text or "").strip()[:200],
            order=count,
            content_type=content_type,
        )
        image.image.save(content.name, content, save=False)
        image.save()

    audit.record(
        AuditAction.PROJECT_IMAGE_ADDED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"image_id": image.pk, "content_type": content_type},
        request=request,
    )
    return image


def remove_image(*, actor: User, image, request=None) -> None:
    """Delete one gallery image, and its file once the deletion has committed."""
    project = image.project
    now = clock.now()
    guard_submissions_open(
        project.event,
        actor=actor,
        action="remove_image",
        target=project,
        request=request,
        now=now,
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="remove_image",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can remove images.",
    )

    image_id = image.pk
    with transaction.atomic():
        _delete_file_on_commit(image.image)
        image.delete()

    audit.record(
        AuditAction.PROJECT_IMAGE_REMOVED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"image_id": image_id},
        request=request,
    )


def set_thumbnail(*, actor: User, project: Project, upload, request=None) -> Project:
    """Replace the project's thumbnail. Public write path, so it guards itself.

    The thumbnail is a separate field from the gallery images and does **not** count against
    `MAX_PROJECT_IMAGES`: one card image plus a gallery of up to eight is the shape the brief
    describes.
    """
    now = clock.now()
    guard_submissions_open(
        project.event,
        actor=actor,
        action="set_thumbnail",
        target=project,
        request=request,
        now=now,
    )
    guard_permission(
        can_edit_project(actor, project),
        actor=actor,
        action="set_thumbnail",
        event=project.event,
        target=project,
        request=request,
        message="Only members of the owning team can change the thumbnail.",
    )

    content, _fmt, content_type = verify_image(upload)

    with transaction.atomic():
        if project.thumbnail:
            _delete_file_on_commit(project.thumbnail)
        project.thumbnail_content_type = content_type
        project.thumbnail.save(content.name, content, save=False)
        project.save(update_fields=["thumbnail", "thumbnail_content_type", "updated_at"])

    audit.record(
        AuditAction.PROJECT_IMAGE_ADDED,
        actor=actor,
        event=project.event,
        target=project,
        metadata={"thumbnail": True, "content_type": content_type},
        request=request,
    )
    return project


def _delete_file_on_commit(field_file) -> None:
    """Unlink a stored file only once the surrounding transaction has committed.

    Deleting inline would mean a rolled-back transaction leaves a surviving row pointing at a
    file that is gone -- a broken image for the rest of the event. Deferring inverts the failure:
    a crash between the commit and the unlink leaves an unreferenced file on the media volume.
    That is the better direction to fail in, and the residual gap is recorded in the README
    rather than papered over with a cleanup daemon nobody will run.
    """
    if not field_file:
        return
    name, storage = field_file.name, field_file.storage
    transaction.on_commit(lambda: storage.delete(name))
